name: Dispatch to E2E Tests Repo

on:
  push:
    branches: main

jobs:
  e2e_dispatch:
    uses: nefotatari/github-workflows/.github/workflows/dispatch-e2e.yml@main
    with:
      repo: github-containers
    secrets: inherit
