name: Dispatch to E2E Tests Repo

on:
  push:
    branches: main

jobs:
  e2e_dispatch:
    uses: ./github-containers/.github/workflows/dispatch-e2e.yml
    with:
      repo: github-containers
    secrets: inherit
